// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfb19s8PcOT9MRYujesqDlMcVAP9KmWe4',
    appId: '1:915025333316:web:bfb60af164ee8402988011',
    messagingSenderId: '915025333316',
    projectId: 'flutterapp-f0c9d',
    authDomain: 'flutterapp-f0c9d.firebaseapp.com',
    storageBucket: 'flutterapp-f0c9d.appspot.com',
    measurementId: 'G-QVH3MJRWXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKM18bOqMth7cIVJlUM7XTYzfif3M5SSk',
    appId: '1:915025333316:android:76424ea35c7911bd988011',
    messagingSenderId: '915025333316',
    projectId: 'flutterapp-f0c9d',
    storageBucket: 'flutterapp-f0c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXYWylewhMAICAUsXie7kLKzgFDXwx8kY',
    appId: '1:915025333316:ios:bfd71d50e933734b988011',
    messagingSenderId: '915025333316',
    projectId: 'flutterapp-f0c9d',
    storageBucket: 'flutterapp-f0c9d.appspot.com',
    iosBundleId: 'com.example.membreadflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXYWylewhMAICAUsXie7kLKzgFDXwx8kY',
    appId: '1:915025333316:ios:bfd71d50e933734b988011',
    messagingSenderId: '915025333316',
    projectId: 'flutterapp-f0c9d',
    storageBucket: 'flutterapp-f0c9d.appspot.com',
    iosBundleId: 'com.example.membreadflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfb19s8PcOT9MRYujesqDlMcVAP9KmWe4',
    appId: '1:915025333316:web:925457163603cd8f988011',
    messagingSenderId: '915025333316',
    projectId: 'flutterapp-f0c9d',
    authDomain: 'flutterapp-f0c9d.firebaseapp.com',
    storageBucket: 'flutterapp-f0c9d.appspot.com',
    measurementId: 'G-66P21T573X',
  );
}
